### ISSUE TITLE
ModbusTCPTransaction: Error message is not shown in a specific case

### ISSUE THREAD

**Issue by simonsample** [steveohara/j2mod#100]
ModbusTCPTransaction.java:134:

`
throw new ModbusIOException("Connection failed for %s:%d", connection.getAddress().toString(), connection.getPort(), ex.getMessage());
`

--> ex.getMessage() is swallowed since there is a format symbol missing in the format-string.

**Comment by steveohara** [comment]
Fixed in 2.5.7
