### ISSUE TITLE
Problem with raspbian RS-485 communication

### ISSUE THREAD

**Issue by pan-henryk** [steveohara/j2mod#112]
I am using j2mod with jSerialComm on raspberry pi/raspbian derived industrial embedded device.
With jSerialComm-2.5.1 and j2mod-2.6.4 (last pair of libraries that work for me, j2mod 2.7.0 is binary incompatible with older jSerialComm versions) everything works fine, but any higher version of jSerialComm it does not, so it seems that the problem I experience was introduced in jSerialComm 2.5.2
Note: I am also posting this in jSerialComm issues, but it may be related to how j2mod uses jSerialComm.

I noticed that any newer version reverts internal com port mode from RS-485 back to rs-232.
Looking at COM port name (/dev/ttySC0) I guess the underlying chip is SC16IS***

## Expected Behavior
Modbus communication should work

## Actual Behavior
Modbus communication does not work

## Steps to Reproduce the Problem

  1. Try to establish modbus communication on SC16IS*** chip (device?) running in RS-485 mode, using  jserialcom version > 2.5.1

## Specifications

  - Version: any with jserialcomm > 2.5.1
  - Platform: Linux
  - Subsystem:
OS version:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Comment by steveohara** [comment]
There isn't anything chip specific in j2mod, so I suspect that if the behaviour has changed, then it will be in jserialcomm or perhaps in the linux serial driver that is being used on Raspbian. I would reach out to Will over there https://fazecast.github.io/jSerialComm/ and see what he says.

**Comment by steveohara** [comment]
I've re-opened this because I think we can mitigate your problem by exposing the RTS control from jserialcomm through j2mod so that you can control it from your application. 
If you're in a hurry, you could do this yourself by providing your own `AbstractSerialConnection` implementation that extends the included version `SerialConnection` and then setting the RS485 values on Open

**Comment by pan-henryk** [comment]
Thank you, I will check it asap.

**Comment by icedaq** [comment]
@pan-henryk We are experiencing the exact same problem. Did you ever find a solution for this?

**Comment by pan-henryk** [comment]
> @pan-henryk We are experiencing the exact same problem. Did you ever find a solution for this?
I stopped at using last working version (jSerialComm-2.5.1 and j2mod-2.6.4) and got distracted by another project.
I plan to revisit it early January to try solution suggested by Steve.

**Comment by icedaq** [comment]
> > @pan-henryk We are experiencing the exact same problem. Did you ever find a solution for this?
> > I stopped at using last working version (jSerialComm-2.5.1 and j2mod-2.6.4) and got distracted by another project.
> > I plan to revisit it early January and try solution suggested by Steve.

Thanks for the update. We tested with the version you mentioned and it works perfectly in our case too. So we will stick with this version for the moment.

**Comment by steveohara** [comment]
Closing this on the basis that https://github.com/steveohara/j2mod/pull/117 has now introduced RS485 mode which should fix the issue
