### ISSUE TITLE
How to add special function in ModbusMaster

### ISSUE THREAD

**Issue by Julien-Faure** [steveohara/j2mod#113]
I would to add special function in ModbusMaster, can you help me please ?

Thank you in advance.

**Comment by steveohara** [comment]
What is the special function you want to add?
You could of course just clone, add the code and create an MR if you're confident it will be good for the library

**Comment by Julien-Faure** [comment]
I wanted to know how to add custom function.

Read registers or write registers value are official functions.


### For example :

I want to create a function with id 80.

This function could reboot a remote slave.

**Comment by steveohara** [comment]
ModbusMaster is an aggregate of other public classes that can do this if you use them directly. I would like to say that I can provide this as a feature of j2mod out of the box but I don't have time I'm afraid.  Take a look at some of the examples under com.ghgande.j2mod.modbus.cmd for more concrete help
