### ISSUE TITLE
How to get response when I write a command using SerialConnection writeBytes() method

### ISSUE THREAD

**Issue by aviral1999099** [steveohara/j2mod#119]
## Expected Behavior
I need a method to read response of the command I sent or in simple words, I want rx for a particular tx. Is their any particular method or we have to add listener, something like that.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: j2mod 2.7.0
  - Platform: Linux ubuntu 18
  - Subsystem:

**Comment by aviral1999099** [comment]
I could not find a method to read a particular register, can you help me here. This is my ultimate task.

**Comment by steveohara** [comment]
I'm not sure what you're asking, seems kind of basic i.e. "how do I read a register using j2mod?"
If that is the case, then please refer to the myriad of examples in the tests or look at the documentation https://github.com/steveohara/j2mod/wiki/Using-j2mod-to-read-from-a-Slave#read-input-registers

**Comment by aviral1999099** [comment]
Thanks for your help. I actually did not phrased the question right. I just
wanted to read register i.e. the value they are holding. I did find it by
the way.
