### ISSUE TITLE
Production use; Repository maintenance

### ISSUE THREAD

**Issue by vinerich** [steveohara/j2mod#129]
Hey there,
we would like to use this project in on of our production system to communicate with legacy line devices.

Some parts of the code seem to have incomplete or sometimes inconsistent documentation.
Also the behavior of some code parts is not ideal for our use case.

### Proposal

To get to a point where we can stand in for a usage of the library we would put some work in on the points that doesn't match our requirements or are inconsistent.

Before we start working on the PRs I'd like to ask a few questions:
1. How active is this repository maintained? Not asking about implementation of fixes or PRs, that is on our side, but the discussion, integration and release of proposed changes.
2. We sadly are restricted to Java 1.8. Are there plans to drop the support of Java 1.8 or should it be supported over a longer period of time?
3. If there are backwards incompatible changes, would it be an issue to release a 3.2.x or even a 4.x.x?

Thanks for your time @steveohara and I'm looking forward to start working on this library!

PS.: The questions may sound harsh, but they aren't meant to. We just want to make sure that we can contribute to the work you already put in and are not forced to do a private fork.

PPS.: Thanks for all the work you already put int and the first prototypes are already working!

**Comment by steveohara** [comment]
No plans to drop support for 1.8, PRs are always welcome (with unit tests of course) so please jump right it
