### ISSUE TITLE
Registry edit popup

### ISSUE THREAD

**Issue by ghost** [steveohara/j2mod#130]
## Expected Behavior
no popups

## Actual Behavior

Registry edit popup after calling the connect() method of a class ModbusSerialMaster.
## Steps to Reproduce the Problem

  1. Each time this method is called, a message appears about the entry in the registry of the del.reg file, which is not in the location shown: C:\Windows\regedit.exe /s F:\MyProject\ ... \app\del. reg ".
  Whether I click yes or no, the connection to the slave device proceeds, but after calling the connect() method again, the registry change window reappears.
 2. When I call the connect() method of the ModbusTCPMaster class, this window is missing.
 3. When an incorrect COM port is given, the window appears avalanche.
## Specifications.

  - Version: j2mod 3.1.1
  - Platform: Windows 10
  - Subsystem:

**Comment by steveohara** [comment]
I'm afraid that is something entirely outside of j2mod, sounds like you're using some sort of exotic COM emulator port and each time something connects to it, Windows is popping a security/admin prompt. Sorry, can't help with that.
Note: - the unit tests on Windows do require that there is a COM loopback emulator installed called [com0com](https://com0com.sourceforge.net/)
