### ISSUE TITLE
Unexpected Connection Closed by peer

### ISSUE THREAD

**Issue by chaos84731** [steveohara/j2mod#132]
## Expected Behavior
Being able to write to coils and registers (single and multiple) without the connection being closed.

## Actual Behavior
Random closure of the connection after writing to coils or registers.

## Steps to Reproduce the Problem

  1. Send command via Simply Modbus TCP Client
![image](https://user-images.githubusercontent.com/33065584/187752206-e216d1cc-1215-4c0b-b1f5-24fb1ec1a103.png)

  1. Have the connection randomly close.
  1.

## Specifications

  - Version:  j2mod:3.0.0'
  - Platform: Android

Hi Randomly I will get a Error 66 (connection closed by peer)  when I am writing registers.  Please help.

Thanks

**Comment by steveohara** [comment]
Is it possible you can reproduce with a unit test?

**Comment by chaos84731** [comment]
Turns out the Error was in my code and updating the Slave while writing values.
