### ISSUE TITLE
WriteMultipleRegisters (Function Code : 0x10) does not work.

### ISSUE THREAD

**Issue by nices96** [steveohara/j2mod#14]
I created a mockup modbus slave(TCP Server) using _**ModbusTCPListener**_ class and test WriteMultipleRegisters function, but error occurred with "Illegal Data Address" message.

I think it is problem with **WriteMultipleRegistersRequest.readData()**'s _**m_Reference = input.readShort();**_.

I changed to **_input.readUnsignedShort()_** and checked it works fine.

**Comment by steveohara** [comment]
I added a test case for this and it works OK - are you using a register number over 32767?

**Comment by steveohara** [comment]
Added fixes for this and other places where the library should be using unsigned shorts
The latest snapshot has the fixes - could you let me know if you see any issues
https://oss.sonatype.org/content/repositories/snapshots/com/ghgande/j2mod/2.0-SNAPSHOT/j2mod-2.0-20160429.141401-1.jar

**Comment by nices96** [comment]
Yes, I did use over 40000 as a register number. Thanks.
