### ISSUE TITLE
Serial port is left hanging in OS if it gets physically disconnected

### ISSUE THREAD

**Issue by MartynasRim** [steveohara/j2mod#144]
## Expected Behavior
If serial port is disconnected - lib should listen to [LISTENING_EVENT_PORT_DISCONNECTED](https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPort.html#LISTENING_EVENT_PORT_DISCONNECTED) event and call [closePort](https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPort.html#closePort()) to prevent hanging serial port reference. More info at - https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPort.html#getCommPorts()

> Note that the array will also include any serial ports that your application currently has open, even if the devices attached to those ports become disconnected. As such, it is important that you always call [closePort()](https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPort.html#closePort()) on a SerialPort object if it becomes disconnected, which is detectable by inspecting the return values from the various read calls or by registering a [SerialPortDataListener](https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPortDataListener.html) for the [LISTENING_EVENT_PORT_DISCONNECTED](https://fazecast.github.io/jSerialComm/javadoc/com/fazecast/jSerialComm/SerialPort.html#LISTENING_EVENT_PORT_DISCONNECTED) event.

## Actual Behavior
If serial port gets disconnected (physically) & connected again while we do have a connection established we will have to ports available in OS. For example `/dev/ttyUSB0` & `/dev/ttyUSB1`.  

## Steps to Reproduce the Problem
  1. Check how many USB ports are available `ls dev | grep ttyUSB`
  1. Connect serial port 
  1. Connect to port using ModbusSerialMaster 
  1. Disconnect port physically and reattach it
  1.  Check how many USB ports are available `ls dev | grep ttyUSB` - there should be 2 more ports allocated

## Specifications

  - Version: 3.2.0
  - Platform: 12 (bookworm) Raspbian 
  - Subsystem:

**Comment by steveohara** [comment]
Merged change into latest snapshot
