### ISSUE TITLE
SerialConnection.writeBytes(SerialConnection.java:199) method did not exist

### ISSUE THREAD

**Issue by sheng930920** [steveohara/j2mod#146]
## Specifications

  - Version: j2mod:3.2.0
  - Platform: Ubuntu 20.04.6 LTS (GNU/Linux 4.19.232 aarch64)
  
<img width="1094" alt="image" src="https://github.com/steveohara/j2mod/assets/13199067/c4102782-c96e-49e4-b022-b3a645fbfe46">

<img width="1259" alt="image" src="https://github.com/steveohara/j2mod/assets/13199067/950eec9b-93a2-41c8-a9a4-f42728c5b390">

<img width="901" alt="image" src="https://github.com/steveohara/j2mod/assets/13199067/490c4f89-e486-48b0-975c-6ca9051d89a3">

**Comment by steveohara** [comment]
I think this may be some sort of miss-match of versions of jSerialComm in your classpath but I'm just about to release 3.2.1 which uses an updated version of jSerialComm so please try that and let me know how you get on
