### ISSUE TITLE
`jSerialComm 2.9.3` dependency blocks `jSerialComm` upgrade

### ISSUE THREAD

**Issue by farzadpanahi** [steveohara/j2mod#149]
Right now the latest stables release `j2mod 3.2.0` is using `jSerialComm 2.9.3` which has numerous critical bugs specially regarding native libraries such as https://github.com/Fazecast/jSerialComm/issues/535. 

Because of the [breaking changes](https://github.com/Fazecast/jSerialComm/releases/tag/v2.10.0) introduced in `jSerialComm 2.10.0`, the user cannot upgrade their `jSerialComm` module.

I can see that `j2mod SNAPHOST 3.2.1` is using `jSerialComm 2.10.3` which is great.

Is releasing `j2mod 3.2.1` in the near road map?

Thanks for all the efforts on this great lib!

**Comment by steveohara** [comment]
To be honest, the release cadence is a bit arbitrary as most people don't use the snapshots so there's seldom a reason to hold anything back.
I'll update the jSerialComm to the latest (2.10.4) and release 3.2.1 today
