### ISSUE TITLE
Retrieve the localPort from opened socket if port is set to 0

### ISSUE THREAD

**Issue by chepseskaf** [steveohara/j2mod#19]
It's possible to set the listening port to 0 in order to bound the first available port, but it's not possible to retriev this port. I think it would be usefull to provides a getter on this port.

**Comment by steveohara** [comment]
It isn't possible to set the listening port to 0. If you attempt to do that, the listener will default to 502.
I assume this is what you mean?

**Comment by steveohara** [comment]
I've added getPort() and getAddress() to AbstractModbusListener
https://oss.sonatype.org/content/repositories/snapshots/com/ghgande/j2mod/2.1-SNAPSHOT/j2mod-2.1-20160531.121216-2.jar
