### ISSUE TITLE
Code requires guards around a number of the functions

### ISSUE THREAD

**Issue by djbr-david** [steveohara/j2mod#22]
Functions such as setParity in the SerialParameters class require a guard against a Null Pointer Exception.

**Comment by steveohara** [comment]
I have added checking where an NPE might occur and created a snapshot. Could you try it and confirm all is now fixed?

https://oss.sonatype.org/content/repositories/snapshots/com/ghgande/j2mod/2.1.3-SNAPSHOT/j2mod-2.1.3-20160630.162817-2.jar

**Comment by djbr-david** [comment]
Checked the code in our app and its all working as far as we are concerned. Thanks for your help.....
