### ISSUE TITLE
j2mod on Android

### ISSUE THREAD

**Issue by adryx92** [steveohara/j2mod#3]
Hello, I'm triyng to use j2mod on an Android application through RTU, but I saw that the library needs the jSerialComm dependency that requires /dev/tti* device. So it does't work with a specific kernel driver.
I am planning to use https://github.com/felHR85/UsbSerial for the low level communication.
Do you have any advice about this?

Thanks

**Comment by steveohara** [comment]
That looks like an interesting way to get UART capability through USB.
Do you have any experience of using that library? I'm thinking particularly in terms of stability and QA.
In any event, I would be happy to add it to j2mod as we could use it here at 4energy

**Comment by djadry** [comment]
Now I'm trying to implement UsbSerial istead of jSerialComm for the serial low level commnication...

**Comment by cusna** [comment]
I too am very interested to use the library j2mod through USB with a converter(type ftdi or prolific)
serial. It would be interesting to incorporate in j2mod the library [https://github.com/felHR85/UsbSerial](https://github.com/felHR85/UsbSerial) or [https://github.com/mik3y/usb-serial-for-android](https://github.com/mik3y/usb-serial-for-android).

**Comment by steveohara** [comment]
This looks like it has been resolved by https://github.com/steveohara/j2mod/pull/28 so I'm closing the ticket in the expectation that this works fine and will be available in an upcoming release
