### ISSUE TITLE
RS485 echo in RTU mode

### ISSUE THREAD

**Issue by davidhuwyler** [steveohara/j2mod#51]
I have echo turned on (rs485 with echo) and using RTU coding. Now not the whole echo gets ignored. The crc of the master-request is taken as slave response.

The problem is in the class
ModbusRTUTransport: 
`
                if (echo) {
                    readEcho(len);
                }
`

there should be 'readEcho(len +2);'
+2 for the 2 crc bytes... the same as in the class ModbusBINTransport. There this is already fixed...
I fixed this locally and it works great!

**Comment by steveohara** [comment]
Added to 2.3.6 snapshot
