### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by apel512** [steveohara/j2mod#55]
Hello
I get the next exception
Please help
[Mine screenshot](https://drive.google.com/file/d/0B6f7PZsS9aWfWVNYZVh5REliN3c/view?usp=sharing)

**Comment by steveohara** [comment]
You haven't included the required slf4j dependencies
For example;
`
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.21</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.21</version>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
`
