### ISSUE TITLE
Serial port errors are swallowed.

### ISSUE THREAD

**Issue by loolooyyyy** [steveohara/j2mod#72]
Running the debugger to see why j2mod doesn't work, I can see that errors about serial port are sent to `AbstractModbusListener` and readable via `getErrors()` but the listener is not accessible through `ModbusSlave`.

By extending `ModbusSlave` (I've called it ListenedSlave, sounds surreal) and making getListener() public, It's possible to get the error message, and perhaps printing it every 1 second. Raising an exception early sound like a better idea. Or perhaps I'm missing something?

By the way, nice job! j2mod is a great re-architecture of the old library.

**Comment by steveohara** [comment]
The whole serial slave implementation is not ideal and there are several things about it that could benefit from a refactor.
Internal components like the listeners should be private, along with quite a few other aspects of the codebase.
However, time is a problem so I've delayed doing too much on correcting this for the time being.

I've added a `getError` method to `ModbusSlave` which will return the listener error, if there is one.

Something to bear in mind, the `getError` will only return an error on slave startup i.e. the value is only set during the initialisation of the slave and the instigation of the listener thread. Values are not continuously written to it when errors occur on the listening thread once it starts.
