### ISSUE TITLE
Why doesn't DigitalOut extend DigitalIn

### ISSUE THREAD

**Issue by Play3r21** [steveohara/j2mod#86]
Why doesn't the interface DigitalOut extend DigitalIn the same way Register extends InputRegister within the procimg sub-directory?

**Comment by steveohara** [comment]
Historical reasons, long since forgotten I imagine - perhaps ask Dieter Wimberger :)

I always thought the semantics of Register extending InputRegister is confusing until you realise that Register means HoldingRegister and similar.
