### ISSUE TITLE
Error in ReadInputDiscretesRequest class SetBitCount() method. Can't access the last address.

### ISSUE THREAD

**Issue by mhjohans** [steveohara/j2mod#87]
## Expected Behavior
It should be possible to create a new ReadInputDiscretesRequest spanning the last possible address (65535).

## Actual Behavior
java.lang.IllegalArgumentException
	at com.ghgande.j2mod.modbus.msg.ReadInputDiscretesRequest.setBitCount(ReadInputDiscretesRequest.java:151)

The  SetBitCount() method does this comparison: count + reference >= 65536. It should be changed to: count + reference > 65536.

## Steps to Reproduce the Problem

  1. Try to create a new ReadInputDiscretesRequest spanning the last possible address (65535)
  2. FAIL!

**Comment by steveohara** [comment]
Added fix to snapshot
