### ISSUE TITLE
[Modbus RTU error] Port [ttyUSB0] cannot be opened or does not exist - Valid ports are: [ttyUSB0]

### ISSUE THREAD

**Issue by yangchengjian** [steveohara/j2mod#89]
https://github.com/thingsboard/thingsboard-gateway/issues/133

**Comment by steveohara** [comment]
I left some ideas on the thingsboard repo so I'm closing this now.
If someone has a similar problem on Linux, take a look at the permissions advice here http://fazecast.github.io/jSerialComm/
