### ISSUE TITLE
How to use AbstractModbusListener to realize real-time monitoring serial data, please provide example

### ISSUE THREAD

**Issue by ArtIsLong** [steveohara/j2mod#97]
How to use AbstractModbusListener to realize real-time monitoring serial data, please provide example

**Comment by steveohara** [comment]
I'm afraid I don't have time to give you an example other than point you to the code base and see how it is implemented yourself. Take a look `AbstractSerialConnection` and where that is implemented, that will give you very low level metrics about the serial comms.

If you need metrics at a higher level then perhaps you should extend `AbstractModbusTransport` with your own implementation and then use that . Take a look through the unit tests for examples e.g. `ModbusMasterFactory.createCustomModbusMaster`
