### ISSUE TITLE
what does the reconnecting in ModbusTCPMaster for?

### ISSUE THREAD

**Issue by bthulu** [steveohara/j2mod#99]
even if reconnecting is false, ModbusTCPMaster still reconnect after socket closed.
it seems that reconnecting has nothing to do

**Comment by steveohara** [comment]
The reconnect flag is added to every transaction - it is the transaction that decides (using that flag) if the connection should be closed after the transaction is complete.
Take a look at ModbusTCPTransactionline 202

Perhaps the name of the flag is a bit miss-leading. What it actually means is "should I close the connection after each transaction?". There is a performance benefit if you keep the connection alive between the master and client if you have a lot of transactions to execute between them
